---
- name: Listen for events on a webhook
  hosts: localhost
  sources:
    - ansible.eda.webhook:
        host: 0.0.0.0
        port: 5001

  rules:
    - name: EDA Test
      condition: event.payload.message == "Event Driven Ansible test webhook" 
      action:
        run_job_template:
          name: EDA Test
          organization: Default
